Originarios/Controllers/PostagensController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Originarios.Models;
using Microsoft.AspNet.Identity;

namespace Originarios.Controllers
{
    [Authorize]
    public class PostagensController : Controller
    {
        private OriginariosEntities db = new OriginariosEntities();

        private Usuario BuscaUsuarioLogado()
        {
            string email = User.Identity.GetUserName();
            return db.Usuario.SingleOrDefault(u => u.email.Equals(email));
        }

        // rota: Meus_Produtos
        // lista os produtos do usuário logado
        public ActionResult Index(char? msg = null)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.msg = msg == 'c' ? "Produto postado com sucesso!!" 
                        : msg == 'd' ? "Produto deletado com sucesso!!"
                        : null;
            IQueryable<Postagem> postagens = db.Postagem.Where(p => p.usuario == usuarioLogado.id_usu);
            return View(postagens.ToList());
        }

        // rota: Criar_Produto
        // chama view para criação de produto
        public ActionResult Create()
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.usuario = usuarioLogado.id_usu;
            return View();
        }

        // POST da view Create
        // cria produto no banco de dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create
        (
            [Bind(Include = "id_post,usuario,titulo,descricao,corpo,valor,nm_img1,vb_img1,nm_img2,vb_img2,nm_img3,vb_img3,nm_img4,vb_img4")] Postagem postagem,
            string base64_img1, string base64_img2, string base64_img3, string base64_img4
        )
        {
            if (ModelState.IsValid)
            {
                postagem.vb_img1 = string.IsNullOrEmpty(base64_img1) ? null : Convert.FromBase64String(base64_img1.Substring(22));
                postagem.vb_img2 = string.IsNullOrEmpty(base64_img2) ? null : Convert.FromBase64String(base64_img2.Substring(22));
                postagem.vb_img3 = string.IsNullOrEmpty(base64_img3) ? null : Convert.FromBase64String(base64_img3.Substring(22));
                postagem.vb_img4 = string.IsNullOrEmpty(base64_img4) ? null : Convert.FromBase64String(base64_img4.Substring(22));

                db.Postagem.Add(postagem);
                db.SaveChanges();
                return RedirectToAction("Index", new { msg = 'c' });
            }
            return View(postagem);
        }

        // rota: Editar_Produto
        // chama view para edição do produto
        public ActionResult Edit(int? id)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (id == null || usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postagem postagem = db.Postagem.Find(id);
            if (postagem == null)
            {
                return HttpNotFound();
            }
            ViewBag.usuario = usuarioLogado.id_usu;
            ViewBag.valor = postagem.valor.ToString().Split(',')[0];
            return View(postagem);
        }

        // POST da view Edit
        // edita produto no banco de dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit
        (
            [Bind(Include = "id_post,usuario,titulo,descricao,corpo,valor,nm_img1,vb_img1,nm_img2,vb_img2,nm_img3,vb_img3,nm_img4,vb_img4")] Postagem postagem,
            string base64_img1, string base64_img2, string base64_img3, string base64_img4
        )
        {
            if (ModelState.IsValid)
            {
                postagem.vb_img1 = string.IsNullOrEmpty(base64_img1) ? null : Convert.FromBase64String(base64_img1.Substring(22));
                postagem.vb_img2 = string.IsNullOrEmpty(base64_img2) ? null : Convert.FromBase64String(base64_img2.Substring(22));
                postagem.vb_img3 = string.IsNullOrEmpty(base64_img3) ? null : Convert.FromBase64String(base64_img3.Substring(22));
                postagem.vb_img4 = string.IsNullOrEmpty(base64_img4) ? null : Convert.FromBase64String(base64_img4.Substring(22));
                
                db.Entry(postagem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = postagem.id_post, editado = true });
            }
            return View(postagem);
        }

        // rota: Ver_Produto
        // chama view para detalhes do produto
        public ActionResult Details(int? id, bool? editado = false)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (id == null || usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postagem postagem = db.Postagem.Find(id);
            if (postagem == null)
            {
                return HttpNotFound();
            }

            ViewBag.msg = editado == true ? "Produto editado com sucesso!!" : null;
            return View(postagem);
        }

        // POST do botão delete da view Details
        // remove produto no banco de dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int? id)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (id == null || usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postagem postagem = db.Postagem.Find(id);
            if (postagem == null)
            {
                return HttpNotFound();
            }
            db.Postagem.Remove(postagem);
            db.SaveChanges();
            return RedirectToAction("Index", new { msg = 'd' });
        }

        [AllowAnonymous]
        // método que busca, renderiza e retorna imagem
        public FileContentResult ObterImgNaView(int id, int img)
        {
            Postagem postagem = db.Postagem.Find(id);
            byte[] vbImg = null;

            switch (img)
            {
                case 1:
                    vbImg = postagem.vb_img1;
                    break;
                case 2:
                    vbImg = postagem.vb_img2;
                    break;
                case 3:
                    vbImg = postagem.vb_img3;
                    break;
                case 4:
                    vbImg = postagem.vb_img4;
                    break;
                default:
                    break;
            }

            return vbImg != null ? new FileContentResult(vbImg, "image/jpeg") : null;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Originarios/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Originarios.Models;

namespace Originarios.Controllers
{
    public class ProdutosController : Controller
    {
        private OriginariosEntities db = new OriginariosEntities();

        // rota: Produtos
        // lista os produtos postados por todos os usuários
        public ActionResult Index(int skip = 0)
        {
            List<Postagem> allPosts = db.Postagem.ToList();
            allPosts.Reverse();
            IEnumerable<Postagem> skipedPosts = allPosts.Skip(skip);
            List<Postagem> filteredPosts = new List<Postagem>();

            for(int i = 0; i < 8; i++)
            {
                try
                {
                    filteredPosts.Add(skipedPosts.ElementAt(i));
                }catch(Exception erro){
                    continue;
                }
            }

            ViewBag.pre = skip - 8;
            ViewBag.pos = skip + 8 >= allPosts.Count ? -1 : skip + 8;
            return View(filteredPosts);
        }

        // rota: Produto/5
        // chama view para detalhes do produto
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postagem postagem = db.Postagem.Find(id);
            if (postagem == null)
            {
                return HttpNotFound();
            }
            string tituloFormatado = removerAcentos(postagem.titulo);
            ViewBag.email = $"mailto:{postagem.Usuario1.email}?subject=Interesse%20em%20produto&body=Ola%2C%20vi%20o%20produto%20-%20{tituloFormatado}%20-%20no%20site%20Originarios%20e%20me%20interessei.%20Como%20adquiro%3F";
            ViewBag.wpp = $"https://api.whatsapp.com/send?phone=55" + $"{postagem.Usuario1.ddd}{postagem.Usuario1.whatsapp}&text=Ola%2C%20vi%20o%20produto%20-%20{tituloFormatado}%20-%20no%20site%20Originarios%20e%20me%20interessei.%20Como%20adquiro%3F";

            return View(postagem);
        }

        private static string removerAcentos(string texto)
        {
            string comAcentos = "ÄÅÁÂÀÃäáâàãÉÊËÈéêëèÍÎÏÌíîïìÖÓÔÒÕöóôòõÜÚÛüúûùÇç";
            string semAcentos = "AAAAAAaaaaaEEEEeeeeIIIIiiiiOOOOOoooooUUUuuuuCc";

            for (int i = 0; i < comAcentos.Length; i++)
            {
                texto = texto.Replace(comAcentos[i].ToString(), semAcentos[i].ToString());
            }
            return texto;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Originarios/Views/Produtos/Details.cshtml
@model Originarios.Models.Postagem

@{
    ViewBag.Title = "Detalhes do Produto";
}

<h2>@ViewBag.Title</h2>

<hr />
@*-------------------------- Inputs texto --------------------------*@
<div class="row">

    <div class="form-group col-12 col-sm-9 pb-4">
        <span><b>Título:</b></span>
        <div class="col-12 col-sm-11">
            <span>@Html.DisplayFor(model => model.titulo)</span>
        </div>
    </div>

    <div class="form-group col-12 col-sm-3 pb-4">
        <span><b>Valor:</b></span>
        <div class="col-6 col-sm-12">
            <span>@Html.DisplayFor(model => model.valor)</span>
        </div>
    </div>

    <div class="form-group col-12 pb-4">
        <span><b>Descrição:</b></span>
        <div class="col-12">
            <span class="text-break">@Html.DisplayFor(model => model.descricao)</span>
        </div>
    </div>

    <div class="form-group col-12 pb-4">
        <span><b>Vendedor:</b></span>
        <div class="col-12">
            <span class="text-break">@Html.DisplayFor(model => model.Usuario1.nome)</span>
        </div>
    </div>

    <div class="form-group col-12 col-sm-9 pb-4">
        <span><b>Cidade:</b></span>
        <div class="col-12 col-sm-11">
            <span>@Html.DisplayFor(model => model.Usuario1.cidade)</span>
        </div>
    </div>

    <div class="form-group col-12 col-sm-3">
        <span><b>Estado:</b></span>
        <div class="col-6 col-sm-12">
            <span>@Html.DisplayFor(model => model.Usuario1.estado)</span>
        </div>
    </div>

</div>
<hr />

@*-------------------------- Imagens --------------------------*@
<div class="row">

    @*----------- Imagem 1 -----------*@
    <div class="col-12 col-sm-6 p-2 borda-sec-img">

        <div class="row mb-2 text-center">
            <span><b>@Html.DisplayFor(model => model.nm_img1)</b></span>
        </div>

        <div class="row mb-2">
            <img class="img-fluid" src="@Url.Action("ObterImgNaView", "Postagens", new { id = Model.id_post, img = 1 })">
        </div>

    </div>

    @*----------- Imagem 2 -----------*@
    <div class="col-12 col-sm-6 p-2 borda-sec-img">

        <div class="row mb-2 text-center">
            <span><b>@Html.DisplayFor(model => model.nm_img2)</b></span>
        </div>

        <div class="row mb-2">
            <img class="img-fluid" src="@Url.Action("ObterImgNaView", "Postagens", new { id = Model.id_post, img = 2 })">
        </div>

    </div>

    @*----------- Imagem 3 -----------*@
    <div class="col-12 col-sm-6 p-2 borda-sec-img">

        <div class="row mb-2 text-center">
            <span><b>@Html.DisplayFor(model => model.nm_img3)</b></span>
        </div>

        <div class="row mb-2">
            <img class="img-fluid" src="@Url.Action("ObterImgNaView", "Postagens", new { id = Model.id_post, img = 3 })">
        </div>

    </div>

    @*----------- Imagem 4 -----------*@
    <div class="col-12 col-sm-6 p-2 borda-sec-img">

        <div class="row mb-2 text-center">
            <span><b>@Html.DisplayFor(model => model.nm_img4)</b></span>
        </div>

        <div class="row mb-2">
            <img class="img-fluid" src="@Url.Action("ObterImgNaView", "Postagens", new { id = Model.id_post, img = 4 })">
        </div>

    </div>

</div>

<hr />
@*-------------------------- Detalhes --------------------------*@
<div class="row">
    <span class="px-0"><b>Detalhes:</b></span>
    <div class="col-12">
        <span class="text-break">@Html.DisplayFor(model => model.corpo)</span>
    </div>
</div>

<hr />
@*-------------------------- Botões --------------------------*@
<div class="row d-flex flex-row justify-content-between justify-content-sm-center">
    @Html.ActionLink("Voltar", "Index", "Produtos", null, htmlAttributes: new { @class = "btn btn-light w-auto" })
    <a href="@ViewBag.email" class="btn btn-primary w-auto mx-sm-4">E-mail</a>
    <a href="@ViewBag.wpp" target="_blank" class="btn btn-success w-auto">WhatsApp</a>
</div>

Originarios/Views/Produtos/Index.cshtml
@model IEnumerable<Originarios.Models.Postagem>

@{ ViewBag.Title = "Produtos"; }
<div style="background-image: url(/Images/4.png); width: 100%; height: 97px; background-size: cover; background-repeat: no-repeat; object-fit: cover; object-position: center top;">
    <br />
    <div><h2 class="text-center" style="text-shadow: 2px 2px 8px #121212;">@ViewBag.Title</h2></div>

    <br />
</div>

<hr style="border-color: #aaa; box-sizing: border-box; width: 100%;" />

@if (ViewBag.msg != null)
{
    <h5 class="text-success">@ViewBag.msg</h5>
}

<div class="container-fluid p-0 d-flex flex-row flex-wrap justify-content-around" style="">

    @foreach (var item in Model)
    {

        <div class="d-inline-block vertical-align: top text-black mt-4 " style="">
            <div class="card" style="width: 15rem;height: 436px;box-shadow: 2px 2px 8px #11111170;">
                @*<div class="card" style="width: 15rem; height: 35rem;">*@

                <a href="@Url.Action("Details", "Produtos", new { id = item.id_post })">

                    <img src="@Url.Action("ObterImgNaView", "Postagens", new { id = item.id_post, img = 1 })" class="card-img-top border " alt="..." style="max-width: 100%; width: 300px; height: 270px; object-fit: cover; object-position: top; ">
                </a>

                <div class="card-body text-center" style="height: 8rem;overflow: auto;">
                    <br />
                    <h5 class="card-title"> @Html.DisplayFor(modelItem => item.titulo) </h5>
                    <h5 class="card-text text-danger" style="">R$ @Html.DisplayFor(modelItem => item.valor)</h5>
                    <p><a href="@Url.Action("Details", "Produtos",new { id = item.id_post })" class="text-info">Ver mais detalhes</a></p>
                </div>

            </div>
        </div>
    }
</div>

<div class="d-flex flex-row justify-content-center mt-4">
    @Html.ActionLink("<<", "Index", "Produtos", routeValues: new { skip = ViewBag.pre }, htmlAttributes: new { @class = ViewBag.pre < 0 ? "btn btn-secondary mx-2" : "btn btn-primary mx-2", disabled = ViewBag.pre < 0 ? "disabled" : "false" })
    @Html.ActionLink(">>", "Index", "Produtos", routeValues: new { skip = ViewBag.pos }, htmlAttributes: new { @class = ViewBag.pos < 0 ? "btn btn-secondary mx-2" : "btn btn-primary mx-2", disabled = ViewBag.pos < 0 ? "disabled" : "false" })
</div>