Originarios/Controllers/PostagensController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Originarios.Models;
using Microsoft.AspNet.Identity;

namespace Originarios.Controllers
{
    [Authorize]
    public class PostagensController : Controller
    {
        private OriginariosEntities db = new OriginariosEntities();

        private Usuario BuscaUsuarioLogado()
        {
            string email = User.Identity.GetUserName();
            return db.Usuario.SingleOrDefault(u => u.email.Equals(email));
        }

        // rota: Meus_Produtos
        // lista os produtos do usuário logado
        public ActionResult Index(char? msg = null)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.msg = msg == 'c' ? "Produto postado com sucesso!!" 
                        : msg == 'd' ? "Produto deletado com sucesso!!"
                        : null;
            IQueryable<Postagem> postagens = db.Postagem.Where(p => p.usuario == usuarioLogado.id_usu);
            return View(postagens.ToList());
        }

        // rota: Criar_Produto
        // chama view para criação de produto
        public ActionResult Create()
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.usuario = usuarioLogado.id_usu;
            return View();
        }

        // POST da view Create
        // cria produto no banco de dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create
        (
            [Bind(Include = "id_post,usuario,titulo,descricao,corpo,valor,nm_img1,vb_img1,nm_img2,vb_img2,nm_img3,vb_img3,nm_img4,vb_img4")] Postagem postagem,
            string base64_img1, string base64_img2, string base64_img3, string base64_img4
        )
        {
            if (ModelState.IsValid)
            {
                postagem.vb_img1 = string.IsNullOrEmpty(base64_img1) ? null : Convert.FromBase64String(base64_img1.Substring(22));
                postagem.vb_img2 = string.IsNullOrEmpty(base64_img2) ? null : Convert.FromBase64String(base64_img2.Substring(22));
                postagem.vb_img3 = string.IsNullOrEmpty(base64_img3) ? null : Convert.FromBase64String(base64_img3.Substring(22));
                postagem.vb_img4 = string.IsNullOrEmpty(base64_img4) ? null : Convert.FromBase64String(base64_img4.Substring(22));

                db.Postagem.Add(postagem);
                db.SaveChanges();
                return RedirectToAction("Index", new { msg = 'c' });
            }
            return View(postagem);
        }

        // rota: Editar_Produto
        // chama view para edição do produto
        public ActionResult Edit(int? id)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (id == null || usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postagem postagem = db.Postagem.Find(id);
            if (postagem == null)
            {
                return HttpNotFound();
            }
            ViewBag.usuario = usuarioLogado.id_usu;
            ViewBag.valor = postagem.valor.ToString().Split(',')[0];
            return View(postagem);
        }

        // POST da view Edit
        // edita produto no banco de dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit
        (
            [Bind(Include = "id_post,usuario,titulo,descricao,corpo,valor,nm_img1,vb_img1,nm_img2,vb_img2,nm_img3,vb_img3,nm_img4,vb_img4")] Postagem postagem,
            string base64_img1, string base64_img2, string base64_img3, string base64_img4
        )
        {
            if (ModelState.IsValid)
            {
                postagem.vb_img1 = string.IsNullOrEmpty(base64_img1) ? null : Convert.FromBase64String(base64_img1.Substring(22));
                postagem.vb_img2 = string.IsNullOrEmpty(base64_img2) ? null : Convert.FromBase64String(base64_img2.Substring(22));
                postagem.vb_img3 = string.IsNullOrEmpty(base64_img3) ? null : Convert.FromBase64String(base64_img3.Substring(22));
                postagem.vb_img4 = string.IsNullOrEmpty(base64_img4) ? null : Convert.FromBase64String(base64_img4.Substring(22));
                
                db.Entry(postagem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = postagem.id_post, editado = true });
            }
            return View(postagem);
        }

        // rota: Ver_Produto
        // chama view para detalhes do produto
        public ActionResult Details(int? id, bool? editado = false)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (id == null || usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postagem postagem = db.Postagem.Find(id);
            if (postagem == null)
            {
                return HttpNotFound();
            }

            ViewBag.msg = editado == true ? "Produto editado com sucesso!!" : null;
            return View(postagem);
        }

        // POST do botão delete da view Details
        // remove produto no banco de dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int? id)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (id == null || usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Postagem postagem = db.Postagem.Find(id);
            if (postagem == null)
            {
                return HttpNotFound();
            }
            db.Postagem.Remove(postagem);
            db.SaveChanges();
            return RedirectToAction("Index", new { msg = 'd' });
        }

        [AllowAnonymous]
        // método que busca, renderiza e retorna imagem
        public FileContentResult ObterImgNaView(int id, int img)
        {
            Postagem postagem = db.Postagem.Find(id);
            byte[] vbImg = null;

            switch (img)
            {
                case 1:
                    vbImg = postagem.vb_img1;
                    break;
                case 2:
                    vbImg = postagem.vb_img2;
                    break;
                case 3:
                    vbImg = postagem.vb_img3;
                    break;
                case 4:
                    vbImg = postagem.vb_img4;
                    break;
                default:
                    break;
            }

            return vbImg != null ? new FileContentResult(vbImg, "image/jpeg") : null;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Originarios/Controllers/PublicacoesController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Originarios.Models;
using Microsoft.AspNet.Identity;

namespace Originarios.Controllers
{
    [Authorize]
    public class PublicacoesController : Controller
    {
        private OriginariosEntities db = new OriginariosEntities();

        private Usuario BuscaUsuarioLogado()
        {
            string email = User.Identity.GetUserName();
            return db.Usuario.SingleOrDefault(u => u.email.Equals(email));
        }

        // rota: Minhas_publicacoes
        // lista os publicações do usuário logado
        public ActionResult Index(char? msg = null)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.msg = msg == 'c' ? "Publicação postada com sucesso!!"
                        : msg == 'd' ? "Publicação deletado com sucesso!!"
                        : null;
            IQueryable<Publicacao> publicacoes = db.Publicacao.Where(p => p.usuario == usuarioLogado.id_usu);
            return View(publicacoes.ToList());
        }

        // rota: Criar_Publicação
        // chama view para criação da publicação
        public ActionResult Create()
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.usuario = usuarioLogado.id_usu;
            return View();
        }

        // POST da view Create
        // cria produto no banco de dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create
        (
            [Bind(Include = "id_public,usuario,titulo,corpo,locali")] Publicacao publicacao
        )
        {
            if (ModelState.IsValid)
            {
                //publicacao.vb_img1 = string.IsNullOrEmpty(base64_img1) ? null : Convert.FromBase64String(base64_img1.Substring(22));
                
                //ver se vai dar certo este add depois que fazer a tabela e ligar ao bd
                db.Publicacao.Add(publicacao);
                db.SaveChanges();
                return RedirectToAction("Index", new { msg = 'c' });
            }
            return View(publicacao);
        }

        // rota: Editar_Publicação
        // chama view para edição da publicação
        public ActionResult Edit(int? id)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (id == null || usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publicacao publicacao = db.Publicacao.Find(id);
            if (publicacao == null)
            {
                return HttpNotFound();
            }
            ViewBag.usuario = usuarioLogado.id_usu;
            return View(publicacao);
        }

        // POST da view Edit
        // edita publicacao no banco de dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit
        (
            [Bind(Include = "id_public,usuario,titulo,corpo,locali")] Publicacao publicacao
        )
        {
            if (ModelState.IsValid)
            {
              //  publicacao.vb_img1 = string.IsNullOrEmpty(base64_img1) ? null : Convert.FromBase64String(base64_img1.Substring(22));
                
                db.Entry(publicacao).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = publicacao.id_public, editado = true });
            }
            return View(publicacao);
        }

        // rota: Ver_Publicação
        // chama view para detalhes do publicação
        public ActionResult Details(int? id, bool? editado = false)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (id == null || usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publicacao publicacao = db.Publicacao.Find(id);
            if (publicacao == null)
            {
                return HttpNotFound();
            }

            ViewBag.msg = editado == true ? "Publicação editada com sucesso!!" : null;
            return View(publicacao);
        }

        // POST do botão delete da view Details
        // remove publicação no banco de dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int? id)
        {
            Usuario usuarioLogado = BuscaUsuarioLogado();
            if (id == null || usuarioLogado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Publicacao publicacao = db.Publicacao.Find(id);
            if (publicacao == null)
            {
                return HttpNotFound();
            }
            db.Publicacao.Remove(publicacao);
            db.SaveChanges();
            return RedirectToAction("Index", new { msg = 'd' });
        }

        [AllowAnonymous]
        /*
        // método que busca, renderiza e retorna imagem
        public FileContentResult ObterImgNaView(int id, int img)
        {
            Publicacao publicacao = db.Publicacao.Find(id);
            byte[] vbImg = null;

            switch (img)
            {
                case 1:
                    vbImg = publicacao.vb_img1;
                    break;
                default:
                    break;
            }

            return vbImg != null ? new FileContentResult(vbImg, "image/jpeg") : null;
        }
        */
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Originarios/Views/Publicacoes/Details.cshtml
@model Originarios.Models.Publicacao

@{ ViewBag.Title = "Detalhes da Publicação"; }

<h2>@ViewBag.Title</h2>

@if (ViewBag.msg != null)
{
<h5 class="text-success">@ViewBag.msg</h5>}

<hr />
@*-------------------------- Inputs texto --------------------------*@
<div class="row">

    <div class="form-group col-12 col-sm-9 pb-4">
        <span><b>Título:</b></span>
        <div class="col-12 col-sm-11">
            <span>@Html.DisplayFor(model => model.titulo)</span>
        </div>
    </div>
</div>
<hr />


<hr />
@*-------------------------- Detalhes --------------------------*@
<div class="row">
    <span class="px-0"><b>Detalhes:</b></span>
    <div class="col-12">
        <span class="text-break">@Html.DisplayFor(model => model.corpo)</span>
    </div>
</div>

<hr />

@*-------------------------- Local --------------------------*@

<div class="row">

    <div class="form-group col-12 col-sm-9 pb-4">
        <span><b>Local:</b></span>
        <div class="col-12 col-sm-11">
            <span>@Html.DisplayFor(model => model.locali)</span>
        </div>
    </div>
</div>
<hr />
@*-------------------------- Botões --------------------------*@
<div class="row">
    @using (Html.BeginForm("Delete", "Publicações", new { id = Model.id_public }, FormMethod.Post, htmlAttributes: new { @class = "px-0 d-flex justify-content-between justify-content-sm-center" }))
    {
@Html.AntiForgeryToken()

                @Html.ActionLink("Voltar", "Index", "Publicacoes", null, htmlAttributes: new { @class = "btn btn-secondary" })
                                @Html.ActionLink("Editar", "Edit", "Publicacoes", routeValues: new { id = Model.id_public }, htmlAttributes: new { @class = "btn btn-warning mx-sm-4" })
                                                <input type="submit" value="Deletar" class="btn btn-danger" />}
</div>

Originarios/Views/Publicacoes/Edit.cshtml
@model Originarios.Models.Publicacao

@{ ViewBag.Title = "Editar Publicação"; }

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Edit", "Publicacoes", FormMethod.Post, htmlAttributes: new { id = "formSalvarPost", @class = "form", role = "form" }))
{
@Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.id_post) @*Associa id do usuário logado à publicação que será editada*@
                                                @Html.HiddenFor(model => model.usuario, new { Value = @ViewBag.usuario })

                                                                <hr /> @*-------------------------- Inputs texto --------------------------*@
<div class="row">

    <div class="form-group col-12 col-sm-9">
        <label class="control-label" for="titulo">Título:</label>
        <div class="col-12 col-sm-11">
            @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { id = "titulo", autofocus = "autofocus", @class = "form-control", @maxlength = "30", required = "required", dataError = "Um título é necessário." } })
            @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group col-12">
        <label class="control-label" for="corpo">Texto:</label>
        <div class="col-12">
            @Html.TextAreaFor(model => model.corpo, 4, 10, htmlAttributes: new { id = "corpo", @class = "form-control", @maxlength = "5000" })
            @Html.ValidationMessageFor(model => model.corpo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group col-12 col-sm-9">
        <label class="control-label" for="titulo">Local:</label>
        <div class="col-12 col-sm-11">
            @Html.EditorFor(model => model.locali, new { htmlAttributes = new { id = "locali", autofocus = "autofocus", @class = "form-control", @maxlength = "30", required = "required", dataError = "Uma localização é necessária." } })
            @Html.ValidationMessageFor(model => model.locali, "", new { @class = "text-danger" })
        </div>
    </div>


</div>

                                                                                                /*<hr /> @*-------------------------- Imagens --------------------------*@
                                                                                                                <div class="row">

                                                                                                                    @*----------- Imagem 1 -----------*@
                                                                                                                    <div class="col-12 col-xl-6 p-2 borda-sec-img">

                                                                                                                        <div class="form-group row mb-2">
                                                                                                                            <label class="control-label" style="padding: 0px" for="nomeImg1">Imagem 1:</label>
                                                                                                                            <div class="col-12 col-sm-5">
                                                                                                                                @Html.EditorFor(model => model.nm_img1, new { htmlAttributes = new { id = "nomeImg1", @class = "form-control", @maxlength = "20" } })
                                                                                                                                @Html.ValidationMessageFor(model => model.nm_img1, "", new { @class = "text-danger" })
                                                                                                                            </div>
                                                                                                                            <div class="col-sm-1"></div>
                                                                                                                            <div class="col-12 col-sm-6">
                                                                                                                                <input type="file" class="form-control" accept="image/*" onchange="carregarImg1(event)">
                                                                                                                                @Html.HiddenFor(model => model.base64_img1, new { id = "hiddenCrop1" })
                                                                                                                            </div>
                                                                                                                        </div>

                                                                                                                        <div class="row">
                                                                                                                            <div class="col-12 col-sm-8 mb-2 mb-sm-0 bg-pre-crop">
                                                                                                                                <img id="preCrop1" style="display: block; max-width: 100%;" src="@Url.Action("ObterImgNaView", "Postagens", new { id = Model.id_post, img = 1 })">
                                                                                                                            </div>

                                                                                                                            <div class="col-12 col-sm-4 d-flex flex-column">
                                                                                                                                <div class="posCrop1 mx-auto mb-2" style="overflow: hidden; width: 200px; height: 200px; margin-left: auto;"></div>
                                                                                                                                <button type="button" id="btnCanvas1" class="btn btn-danger">Salvar Imagem</button>
                                                                                                                            </div>
                                                                                                                        </div>

                                                                                                                    </div>*/

                                                                                                                   

                                                                                                                                <hr /> @*-------------------------- Botões --------------------------*@
                                                                                                                                                <div class="row">
                                                                                                                                                    <div class="col-6 px-2 d-flex justify-content-end">
                                                                                                                                                        @Html.ActionLink("Voltar", "Index", "Publicacoes", routeValues: new { id = Model.id_public }, htmlAttributes: new { @class = "btn btn-secondary" })
                                                                                                                                                    </div>
                                                                                                                                                    <div class="col-6 px-2">
                                                                                                                                                        <input type="button" id="btnSalvarProduto" value="Salvar" class="btn btn-success" />
                                                                                                                                                    </div>
                                                                                                                                                </div>}

Originarios/Views/Publicacoes/Index.cshtml
@model IEnumerable<Originarios.Models.Publicacao>

@{ ViewBag.Title = "Minhas Publicações"; }

<h2>@ViewBag.Title</h2>

@if (ViewBag.msg != null)
{
<h5 class="text-success">@ViewBag.msg</h5>}

<p>
    @Html.ActionLink("Criar novo", "Create", "publicacoes", null, htmlAttributes: new { @class = "btn btn-warning" })
</p>

<div class="container-fluid p-0 d-flex flex-row flex-wrap justify-content-around" style="">

    @foreach (var item in Model)
    {

<div class="d-inline-block vertical-align: top text-black mt-4 " style="">
    <div class="card" style="width: 15rem; height: 35rem;">

        <a href="@Url.Action("Details", "Publicacoes", new { id = item.id_public })">

        </a>

        <div class="card-body" style="height: 8rem;overflow: auto;">
            <br />
            <h5 class="card-title"> @Html.DisplayFor(modelItem => item.titulo) </h5>
            <h5 class="card-text text-danger" style="">@Html.DisplayFor(modelItem => item.titulo)</h5>
            <p><a href="@Url.Action("Details", "Publicacoes",new { id = item.id_public })" class="text-info">Ver mais detalhes</a></p>
        </div>

    </div>
</div>}
</div>